# Generated by Django 2.0.2 on 2018-02-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='おもい')),
                ('type', models.CharField(blank=True, choices=[('', ' '), ('C', 'かっけー'), ('H', 'あつい'), ('U', 'やくだつ'), ('S', 'おひろめ')], default='', max_length=1, verbose_name='かんじ')),
            ],
        ),
        migrations.CreateModel(
            name='Tsubu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='みだし')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='ありか')),
                ('description', models.TextField(blank=True, verbose_name='おまけ')),
                ('image', models.ImageField(blank=True, height_field=90, upload_to='', verbose_name='さしえ', width_field=160)),
                ('parent', models.ManyToManyField(blank=True, related_name='_tsubu_parent_+', to='cms.Tsubu', verbose_name='そろえ')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Tsubu', verbose_name='かんじ'),
        ),
    ]
