# Generated by Django 2.0.2 on 2018-02-12 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolFlg', models.BooleanField(default=False, verbose_name='かっけー')),
                ('hotFlg', models.BooleanField(default=False, verbose_name='げきあつ')),
                ('usefulFlg', models.BooleanField(default=False, verbose_name='おやくだち')),
                ('spreadFlg', models.BooleanField(default=False, verbose_name='おひろめ')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='しるし')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='おもひ')),
                ('creatorName', models.CharField(blank=True, max_length=255, verbose_name='つくりて')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='つくりどき')),
                ('updaterName', models.CharField(blank=True, max_length=255, verbose_name='なおして')),
                ('updaterOn', models.DateTimeField(auto_now=True, verbose_name='なおしどき')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='ならび')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='ありか')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='つけたし')),
                ('creatorName', models.CharField(blank=True, max_length=255, verbose_name='つくりて')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='つくりどき')),
                ('updaterName', models.CharField(blank=True, max_length=255, verbose_name='なおして')),
                ('updaterOn', models.DateTimeField(auto_now=True, verbose_name='なおしどき')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=90, upload_to='', verbose_name='さしえ', width_field=160)),
                ('isTemp', models.BooleanField(default=False, verbose_name='一時フラグ')),
                ('creatorName', models.CharField(blank=True, max_length=255, verbose_name='つくりて')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='とき')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='みだし')),
                ('creatorName', models.CharField(blank=True, max_length=255, verbose_name='つくりて')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='つくりどき')),
                ('updaterName', models.CharField(blank=True, max_length=255, verbose_name='なおして')),
                ('updaterOn', models.DateTimeField(auto_now=True, verbose_name='なおしどき')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updaterId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Image', verbose_name='さしえ'),
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.List', verbose_name='そろい'),
        ),
        migrations.AddField(
            model_name='content',
            name='updaterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Content', verbose_name='かんじ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updaterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
