# Generated by Django 2.0.2 on 2018-02-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180204_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='みだし')),
                ('description', models.TextField(blank=True, verbose_name='つけたし')),
                ('parent', models.ManyToManyField(blank=True, related_name='_list_parent_+', to='cms.List', verbose_name='そろい')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ならび'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='おもひ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(blank=True, choices=[('', ' '), ('C', 'かっけー'), ('H', 'あっちー'), ('U', 'やくだつ'), ('S', 'おひろめ')], default='', max_length=1, verbose_name='かんじ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, verbose_name='つけたし'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='parent',
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.List', verbose_name='そろい'),
        ),
    ]
