# Generated by Django 2.0.2 on 2018-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180204_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=90, upload_to='', verbose_name='さしえ', width_field=160)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='coolFlg',
            field=models.BooleanField(default=False, verbose_name='かっけー'),
        ),
        migrations.AddField(
            model_name='comment',
            name='hotFlg',
            field=models.BooleanField(default=False, verbose_name='あっちー'),
        ),
        migrations.AddField(
            model_name='comment',
            name='spreadFlg',
            field=models.BooleanField(default=False, verbose_name='おひろめ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='usefulFlg',
            field=models.BooleanField(default=False, verbose_name='おやくだち'),
        ),
        migrations.AddField(
            model_name='list',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='しるし'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='つけたし'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Image', verbose_name='さしえ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.List', verbose_name='そろい'),
        ),
    ]
